<?php
return [
  'header' => [
    'title' => 'Avís Legal',
    'robots' => ['index' => 'index','follow' => 'follow'],
    'description' => 'Avís Legal de Projectes i Disseny· Crea una botiga online · Disseny únic i professional · Optimitzada per mòbils · Correu Electrònic · Suport tècnic · SSL · Multidioma',
  ],
  'p' => "<p> <strong> IDENTITAT DEL TITULAR DEL LLOC WEB </strong> </p>
<p> Projectes i Disseny Incafe2000 <br /> Andreu Casamitjana Carrillo <br /> Plaça Illa, 12-15A Pol. Ind. Illa Sud <br /> 08650 - Sallent (Barcelona) <br / > CIF: B65002768 </p>
<p> <strong> TERMES LEGALS I CONDICIONS </strong> </p>
<p> La utilització d'aquest lloc Web atribueix al navegant la condició d'Usuari del lloc, la qual cosa implica l'adhesió a les presents condicions a la versió publicada en el moment en que s'accedeixi a aquest. Per això, recomana a l'Usuari llegir les mateixes atentament cada vegada que accedeixi al lloc Web. L'accés a determinats continguts oferts a través d'aquest lloc web pot trobar-se sotmès a certes condicions particulars pròpies que, segons els casos, substitueixen, completen i / o modifiquen aquestes condicions generals. Per tant, amb anterioritat a l'accés i / o utilització d'aquests continguts, l'usuari ha de llegir atentament també les corresponents condicions particulars. Projectes i Disseny podrà alterar en qualsevol moment i sense previ avís, el disseny, presentació i / o configuració del lloc Web, així com alguns o tots els Continguts, i modificar les condicions generals i / o condicions particulars requerides per utilitzar els mateixos. </p>
<p> </p>
<p> <strong> RESPONSABILITAT I GARANTIA DE Projectes i Disseny </strong> </p>
<p> ACCÉS </p>
<p> Amb caràcter general, els Usuaris podran accedir al lloc web de forma lliure i gratuïta. No obstant això, Projectes i Disseny es reserva conforme a la legislació vigent el dret de limitar l'accés a determinades àrees del lloc web. En aquests casos, com a requisit previ per poder accedir al servei, l'Usuari haurà de registrar facilitant tota la informació sol·licitada, de forma actualitzada i real (vegeu política de privacitat). L'ús de la contrasenya és personal i intransferible, no estant permesa la cessió, ni tan sols temporal, a tercers. En aquest sentit, l'Usuari es compromet a fer un ús diligent ia mantenir en secret la mateixa, assumint tota responsabilitat per les conseqüències de la seva divulgació a tercers. </p>
<p> CONTINGUTS </p>
<p> Projectes i Disseny es reserva el dret a interrompre l'accés al seu lloc Web, així com la prestació de qualsevol o de tots els Continguts que es presten a través del mateix en qualsevol moment i sense previ avís, ja sigui per motius tècnics , de seguretat, de control, de manteniment, per fallades de subministrament elèctric o per qualsevol altra causa. Aquesta interrupció podrà tenir caràcter temporal o definitiu, en aquest cas es comunicarà tal circumstància als Usuaris, qui podran patir la pèrdua, si escau, de la informació emmagatzemada en els diferents serveis. En conseqüència, Projectes i Disseny no garanteix la fiabilitat, la disponibilitat ni la continuïtat del seu lloc Web ni dels Continguts, tant els propis com els d'altres llocs web als quals es pugui accedir mitjançant enllaços, de manera que la utilització dels mateixos per part de l'Usuari es porta a terme pel seu propi compte i risc, sense que, en cap moment, puguin exigir responsabilitats a eL Projectes i Disseny en aquest sentit. EL Projectes i Disseny no serà responsable de qualsevol tipus de perjudici, pèrdues, reclamacions o despeses de cap tipus, de la Informació adquirida o accedida per oa través del lloc web, de virus informàtics, de fallades operatives o d'interrupcions en el servei o transmissió , o fallades en la línia. Queda prohibit transmetre o enviar a través del lloc web qualsevol contingut il·legal o il·lícit, virus informàtics, o missatges que, en general, afectin o violin drets de Projectes i Disseny o de tercers. </p>
<p> </p>
<p> <strong> Propietat industrial i intel·lectual </strong> </p>
<p> Aquesta web és propietat de Projectes i Disseny. Els drets de Propietat Intel·lectual i d'explotació i reproducció d'aquesta Web, de les seves pàgines, pantalles, la informació que contenen, la seva aparença i disseny, així com els vincles que s'estableixin des d'ella a altres pàgines, són propietat exclusiva d'aquest, llevat que s'especifiqui una altra cosa. Totes les denominacions, dissenys i / o logotips que componen aquesta pàgina són marques degudament registrades. Qualsevol ús indegut de les mateixes per persona diferent del seu legítim titular podrà ser perseguit de conformitat amb la legislació vigent. Els drets de propietat intel·lectual i marques de tercers estan destacats convenientment i han de ser respectats per tot aquell que accedeixi a la web. Només per a ús personal i privat es permet descarregar els continguts, copiar o imprimir qualsevol pàgina d'aquesta web. Queda prohibit reproduir, transmetre, modificar o suprimir la informació, contingut o advertències d'aquesta web sense la prèvia autorització escrita de Projectes i Disseny. </p>
<p> </p>
<p> <strong> LEGISLACIÓ APLICABLE </strong> </p>
<p> Les presents condicions generals es regiran per la legislació espanyola. </p>
<p> </p>
<p> <strong> POLÍTICA DE PRIVACITAT </strong> </p>
<p> A l'efecte del que disposa la normativa vigent relativa a la protecció de dades de caràcter personal, Projectes i Disseny informa que les dades personals que ens pogués facilitar durant la navegació pel nostre lloc web seran incorporades a un tractament de dades el responsable és Projectes i Disseny, amb l'única finalitat de poder gestionar la seva petició. Només en el cas que l'Usuari hagi donat el seu consentiment exprés, EL Projectes i Disseny li enviarà informació tècnica, operativa i comercial, per qualsevol mitjà, inclòs el correu electrònic i / o mitjà equivalent, sobre productes, serveis, ofertes i novetats que considerem d'interès per a l'Usuari. EL Projectes i Disseny es compromet a complir la seva obligació de secret de les dades de caràcter personal i del seu deure de guardar i adoptarà les mesures necessàries per evitar la seva alteració, pèrdua, tractament o accés no autoritzat, tenint en compte en tot moment de l'estat de la tecnologia, complint amb les mesures de seguretat tècniques i organitzatives. Finalment, l'informem sobre la possibilitat d'exercitar els drets d'accés, rectificació, cancel·lació i oposició mitjançant formulari adreçat a l'administrador del sistema. </p>"
];
?>
