<?php
return [
  'header' => [
    'title' => 'Aviso Legal',
    'robots' => ['index' => 'index','follow' => 'follow'],
    'description' => 'Aviso Legal de Projectes i Disseny · Crear una tienda online · Diseño único y profesional · Optimizada para móviles · Correo Electrónico · Soporte técnico · SSL · Multidioma',
  ],
  'p' => '<p><strong>IDENTIDAD DEL TITULAR DEL SITIO WEB</strong></p>
<p><b>Projectes i Disseny Incafe2000</b><br />Andreu Casamitjana Carrillo<br />Plaça Illa, 12-15A Pol. Ind. Illa Sud<br />08650 - Sallent (Barcelona) <br />CIF: B65002768</p>
<p><strong>TÉRMINOS LEGALES Y CONDICIONES</strong></p>
<p>La utilización de este sitio Web atribuye al navegante la condición de Usuario del sitio, lo cual implica la adhesión a las presentes condiciones en la versión publicada en el momento en que se acceda al mismo. Por ello, recomienda al Usuario leer las mismas atentamente cada vez que acceda al sitio Web. El acceso a determinados Contenidos ofrecidos a través de este sitio Web puede encontrarse sometido a ciertas condiciones particulares propias que, según los casos, sustituyen, completan y/o modifican estas condiciones generales. Por tanto, con anterioridad al acceso y/o utilización de dichos Contenidos, el Usuario ha de leer atentamente también las correspondientes condiciones particulares. Projectes i Disseny podrá alterar en cualquier momento y sin previo aviso, el diseño, presentación y/o configuración del sitio Web, así como algunos o todos los Contenidos, y modificar las condiciones generales y/o condiciones particulares requeridas para utilizar los mismos.</p>
<p></p>
<p><strong>RESPONSABILIDAD Y GARANTÍA DE Projectes i Disseny</strong></p>
<p>ACCESO</p>
<p>Con carácter general, los Usuarios podrán acceder al sitio Web de forma libre y gratuita. No obstante, Projectes i Disseny se reserva conforme a la legislación vigente el derecho de limitar el acceso a determinadas áreas del sitio Web. En estos casos, como requisito previo para poder acceder al servicio, el Usuario deberá registrarse facilitando toda la información solicitada, de forma actualizada y real (véase política de privacidad). El uso de la contraseña es personal e intransferible, no estando permitida la cesión, ni siquiera temporal, a terceros. En tal sentido, el Usuario se compromete a hacer un uso diligente y a mantener en secreto la misma, asumiendo toda responsabilidad por las consecuencias de su divulgación a terceros.</p>
<p>CONTENIDOS</p>
<p>Projectes i Disseny se reserva el derecho a interrumpir el acceso a su sitio Web, así como la prestación de cualquiera o de todos los Contenidos que se prestan a través del mismo en cualquier momento y sin previo aviso, ya sea por motivos técnicos, de seguridad, de control, de mantenimiento, por fallos de suministro eléctrico o por cualquier otra causa. Dicha interrupción podrá tener carácter temporal o definitivo, en cuyo caso se comunicará tal circunstancia a los Usuarios, quienes podrán sufrir la pérdida, en su caso, de la información almacenada en los distintos servicios. En consecuencia, Projectes i Disseny no garantiza la fiabilidad, la disponibilidad ni la continuidad de su sitio Web ni de los Contenidos, tanto los propios como los de otros sitios Web a los que se pueda acceder mediante enlaces, por lo que la utilización de los mismos por parte del Usuario se lleva a cabo por su propia cuenta y riesgo, sin que, en ningún momento, puedan exigirse responsabilidades a EL Projectes i Disseny en este sentido. EL Projectes i Disseny no será responsable de cualquier tipo de perjuicio, pérdidas, reclamaciones o gastos de ningún tipo, de la Información adquirida o accedida por o a través del sitio Web, de virus informáticos, de fallos operativos o de interrupciones en el servicio o transmisión, o fallos en la línea. Queda prohibido transmitir o enviar a través del sitio Web cualquier contenido ilegal o ilícito, virus informáticos, o mensajes que, en general, afecten o violen derechos de Projectes i Disseny o de terceros.</p>
<p></p>
<p><strong>PROPIEDAD INDUSTRIAL E INTELECTUAL</strong></p>
<p>Esta Web es propiedad de Projectes i Disseny. Los derechos de Propiedad Intelectual y derechos de explotación y reproducción de esta Web, de sus páginas, pantallas, la información que contienen, su apariencia y diseño, así como los vínculos que se establezcan desde ella a otras páginas, son propiedad exclusiva de éste, salvo que se especifique otra cosa. Todas las denominaciones, diseños y/o logotipos que componen esta página son marcas debidamente registradas. Cualquier uso indebido de las mismas por persona diferente de su legítimo titular podrá ser perseguido de conformidad con la legislación vigente. Los derechos de propiedad intelectual y marcas de terceros están destacados convenientemente y deben ser respetados por todo aquel que acceda a la Web. Solo para uso personal y privado se permite descargar los contenidos, copiar o imprimir cualquier página de esta Web. Queda prohibido reproducir, transmitir, modificar o suprimir la información, contenido u advertencias de esta Web sin la previa autorización escrita de Projectes i Disseny.</p>
<p></p>
<p><strong>LEGISLACIÓN APLICABLE</strong></p>
<p>Las presentes condiciones generales se regirán por la legislación española.</p>
<p></p>
<p><strong>POLÍTICA DE PRIVACIDAD</strong></p>
<p>A los efectos de lo dispuesto en la normativa vigente relativa a la protección de datos de carácter personal, Projectes i Disseny informa que los datos personales que nos pudiera facilitar durante la navegación por nuestro sitio Web serán incorporados a un tratamiento de datos cuyo responsable es Projectes i Disseny, con la única finalidad de poder gestionar su petición. Solamente en el caso de que el Usuario haya dado su consentimiento expreso, EL Projectes i Disseny le enviará información técnica, operativa y comercial, por cualquier medio, incluido el correo electrónico y/o medio equivalente, sobre productos, servicios, ofertas y novedades que consideremos de interés para el Usuario. EL Projectes i Disseny se compromete al cumplimiento de su obligación de secreto de los datos de carácter personal y de su deber de guardarlos y adoptará las medidas necesarias para evitar su alteración, pérdida, tratamiento o acceso no autorizado, habida cuenta en todo momento del estado de la tecnología, cumpliendo con las medidas de seguridad técnicas y organizativas. Por último, le informamos sobre la posibilidad de ejercitar los derechos de acceso, rectificación, cancelación y oposición mediante formulario dirigido al administrador del sistema.</p>'
];
?>
